(function(){'use strict';
const S='roadToP1PartnersV100',R='roadToP1PartnersResearchV100',ST=['À étudier','À contacter','Contacté','Rendez-vous','Proposition envoyée','Négociation','Signé'];
const T={dashboard:['Tableau de bord','Piloter la prospection, les relances, les propositions et les partenariats depuis un seul endroit.'],research:['Recherche','Définir les entreprises à cibler et conserver un brief de prospection clair.'],prospects:['Prospects','Qualifier les entreprises, les contacts et les opportunités de partenariat.'],pipeline:['Pipeline','Suivre chaque prospect depuis la recherche jusqu’à la signature.'],followups:['Relances','Voir immédiatement qui doit être recontacté et quand.'],partners:['Partenaires','Suivre les partenariats signés, les montants et les renouvellements.'],reports:['Rapports','Mesurer le potentiel, la conversion et la qualité du portefeuille.']};
let D={items:[]},edit=null;const $=id=>document.getElementById(id),n=v=>+v||0,esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=v=>new Intl.NumberFormat('fr-FR',{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(n(v));
const today=()=>new Date().toISOString().slice(0,10),fd=v=>v?v.split('-').reverse().join('/'):'—',prio=s=>s>=75?'A':s>=50?'B':'C',sc=s=>s>=75?'high':s>=50?'mid':'low',uid=()=>('p'+Date.now().toString(36)+Math.random().toString(36).slice(2,6));
function toast(x){let e=$('toast');e.textContent=x;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1800)}
function load(){try{let x=JSON.parse(localStorage.getItem(S)||'null');if(x&&Array.isArray(x.items))D=x}catch(e){}}function save(){localStorage.setItem(S,JSON.stringify(D))}function item(id){return D.items.find(x=>x.id===id)}
function fill(){let o=ST.map(x=>`<option>${esc(x)}</option>`).join('');$('fStatus').innerHTML=o;$('pStatus').innerHTML='<option value="all">Toutes les étapes</option>'+o}
function stats(){let sg=D.items.filter(x=>x.status==='Signé'),op=D.items.filter(x=>x.status!=='Signé'),t=today();return{total:D.items.length,a:D.items.filter(x=>x.priority==='A').length,rel:D.items.filter(x=>x.nextDate&&x.nextDate<=t&&x.status!=='Signé').length,prop:D.items.filter(x=>['Proposition envoyée','Négociation'].includes(x.status)).length,pot:op.reduce((a,x)=>a+n(x.potential),0),sig:sg.reduce((a,x)=>a+n(x.signed),0),p:sg.length,rf:D.items.filter(x=>x.nextDate).length,av:D.items.length?Math.round(D.items.reduce((a,x)=>a+n(x.score),0)/D.items.length):0}}
function bind(){document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>open(b.dataset.open));document.querySelectorAll('[data-plus7]').forEach(b=>b.onclick=()=>{let x=item(b.dataset.plus7);if(!x)return;let d=x.nextDate?new Date(x.nextDate+'T12:00:00'):new Date();d.setDate(d.getDate()+7);x.nextDate=d.toISOString().slice(0,10);save();render();toast('Relance reportée de 7 jours')})}
function dashboard(){let s=stats();[['kpiProspects',s.total],['kpiA',s.a],['kpiFollowups',s.rel],['kpiProposals',s.prop],['kpiPotential',money(s.pot)],['kpiSigned',money(s.sig)],['rConversion',s.total?Math.round(s.p/s.total*100)+'%':'0%'],['rAvgSigned',money(s.p?s.sig/s.p:0)],['rOpen',money(s.pot)],['rAvgScore',s.av],['rFollowups',s.rf],['rPartners',s.p]].forEach(a=>$(a[0]).textContent=a[1]);
$('pipelineMini').innerHTML=ST.map(st=>`<div class="stage-mini"><div class="n">${D.items.filter(x=>x.status===st).length}</div><div class="t">${esc(st)}</div></div>`).join('');let top=D.items.slice().sort((a,b)=>n(b.score)-n(a.score)).slice(0,5);$('topProspects').innerHTML=top.length?top.map(x=>`<div style="display:flex;justify-content:space-between;align-items:center;gap:10px;padding:9px 0;border-bottom:1px solid rgba(255,255,255,.06)"><div><b>${esc(x.company)}</b><div style="font-size:10px;color:#8b979f">${esc(x.sector||'Secteur non défini')}</div></div><div><span class="priority ${x.priority}">${x.priority}</span> <span class="score ${sc(x.score)}"><span class="score-dot"></span>${n(x.score)}</span> <button class="btn small" data-open="${x.id}">Ouvrir</button></div></div>`).join(''):'<div class="empty">Ajoutez vos premiers prospects pour faire apparaître les priorités.</div>';
let urgent=D.items.filter(x=>x.nextDate&&x.nextDate<=today()&&x.status!=='Signé').sort((a,b)=>a.nextDate.localeCompare(b.nextDate));$('followupMeta').textContent=urgent.length+' action'+(urgent.length>1?'s':'');$('dashboardFollowups').innerHTML=urgent.map(x=>`<tr><td><b>${esc(x.company)}</b></td><td>${esc(x.contact||'—')}</td><td><span class="status-pill">${esc(x.status)}</span></td><td>${fd(x.nextDate)}</td><td>${money(x.potential)}</td><td><button class="btn small" data-open="${x.id}">Ouvrir</button></td></tr>`).join('');$('dashboardFollowupsEmpty').classList.toggle('hidden',!!urgent.length)}
function prospects(){let q=($('pSearch').value||'').toLowerCase(),st=$('pStatus').value,pr=$('pPriority').value,se=$('pSector').value;let secs=[...new Set(D.items.map(x=>x.sector).filter(Boolean))].sort();let cur=se;$('pSector').innerHTML='<option value="all">Tous secteurs</option>'+secs.map(x=>`<option>${esc(x)}</option>`).join('');if(secs.includes(cur))$('pSector').value=cur;let L=D.items.filter(x=>(!q||[x.company,x.contact,x.sector,x.location,x.email,x.tags].join(' ').toLowerCase().includes(q))&&(st==='all'||x.status===st)&&(pr==='all'||x.priority===pr)&&(se==='all'||x.sector===se)).sort((a,b)=>n(b.score)-n(a.score));$('prospectBody').innerHTML=L.map(x=>`<tr><td><b>${esc(x.company)}</b><div style="font-size:10px;color:#76838c">${esc(x.location||'')}</div></td><td>${esc(x.sector||'—')}</td><td><span class="score ${sc(x.score)}"><span class="score-dot"></span>${n(x.score)}</span></td><td><span class="priority ${x.priority}">${x.priority}</span></td><td><span class="status-pill">${esc(x.status)}</span></td><td>${esc(x.contact||'—')}</td><td>${money(x.potential)}</td><td>${fd(x.nextDate)}</td><td><button class="btn small" data-open="${x.id}">Fiche</button></td></tr>`).join('');$('prospectEmpty').classList.toggle('hidden',!!L.length)}
function pipeline(){$('kanban').innerHTML=ST.map(st=>{let L=D.items.filter(x=>x.status===st).sort((a,b)=>n(b.score)-n(a.score));return`<div class="kan-col"><div class="kan-head"><span>${esc(st)}</span><span class="kan-count">${L.length}</span></div><div class="kan-body">${L.length?L.map(x=>`<div class="kan-card" data-open="${x.id}"><div class="name">${esc(x.company)}</div><div class="sector">${esc(x.sector||'Secteur non défini')}</div><div class="row"><span class="priority ${x.priority}">${x.priority}</span><span class="score ${sc(x.score)}"><span class="score-dot"></span>${n(x.score)}</span></div><div class="row"><span style="font-size:10px;color:#8d99a1">Potentiel</span><span class="money">${money(st==='Signé'?x.signed:x.potential)}</span></div></div>`).join(''):'<div style="font-size:10px;color:#66737c;padding:8px">Aucun prospect</div>'}</div></div>`}).join('')}
function followups(){let L=D.items.filter(x=>x.nextDate).sort((a,b)=>a.nextDate.localeCompare(b.nextDate));$('followupBody').innerHTML=L.map(x=>`<tr><td>${fd(x.nextDate)}</td><td><b>${esc(x.company)}</b></td><td>${esc(x.contact||'—')}</td><td>${esc(x.nextAction||'Relancer')}</td><td><span class="status-pill">${esc(x.status)}</span></td><td><span class="priority ${x.priority}">${x.priority}</span></td><td><button class="btn small" data-open="${x.id}">Ouvrir</button> <button class="btn small" data-plus7="${x.id}">+7 j</button></td></tr>`).join('');$('followupEmpty').classList.toggle('hidden',!!L.length)}
function partners(){let L=D.items.filter(x=>x.status==='Signé').sort((a,b)=>n(b.signed)-n(a.signed));$('partnersMeta').textContent=L.length+' partenaire'+(L.length>1?'s':'');$('partnersBody').innerHTML=L.map(x=>`<tr><td><b>${esc(x.company)}</b></td><td>${esc(x.contact||'—')}</td><td><b>${money(x.signed)}</b></td><td>${fd(x.startDate)}</td><td>${fd(x.renewal)}</td><td>${esc((x.notes||'').slice(0,90))}</td><td><button class="btn small" data-open="${x.id}">Ouvrir</button></td></tr>`).join('');$('partnersEmpty').classList.toggle('hidden',!!L.length)}
function reports(){let V=ST.map(st=>({st,v:D.items.filter(x=>x.status===st).reduce((a,x)=>a+n(st==='Signé'?x.signed:x.potential),0)})),mx=Math.max(1,...V.map(x=>x.v));$('reportStages').innerHTML=V.map(x=>`<div style="margin:9px 0"><div style="display:flex;justify-content:space-between;font-size:11px"><b>${esc(x.st)}</b><span>${money(x.v)}</span></div><div style="height:8px;background:#0b1115;border-radius:99px;margin-top:5px;overflow:hidden"><div style="height:100%;width:${Math.round(x.v/mx*100)}%;background:linear-gradient(90deg,#b91d27,#ef333a);border-radius:99px"></div></div></div>`).join('')}
function render(){dashboard();prospects();pipeline();followups();partners();reports();bind()}
function sw(v){document.querySelectorAll('.view').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.nav button').forEach(x=>x.classList.toggle('active',x.dataset.view===v));$('view-'+v).classList.add('active');$('pageTitle').textContent=T[v][0];$('pageSubtitle').textContent=T[v][1];render()}
function reset(){edit=null;$('modalTitle').textContent='Nouveau prospect';['fCompany','fSector','fLocation','fWebsite','fContact','fRole','fEmail','fPhone','fLinkedin','fPotential','fAsk','fSigned','fLastContact','fNextDate','fNextAction','fStartDate','fRenewal','fTags','fAngle','fNotes'].forEach(id=>$(id).value='');$('fStatus').value=ST[0];$('fPriority').value='B';[['sFit',10],['sBudget',10],['sContact',8],['sLocal',8],['sSport',8],['sRse',8]].forEach(a=>$(a[0]).value=a[1]);$('approachWrap').classList.add('hidden');$('deleteProspectBtn').classList.add('hidden');score()}
function open(id){let x=item(id);if(!x)return;reset();edit=id;$('modalTitle').textContent=x.company;['Company','Sector','Location','Website','Contact','Role','Email','Phone','Linkedin','Potential','Ask','Signed','LastContact','NextDate','NextAction','StartDate','Renewal','Tags','Angle','Notes'].forEach(k=>{let key=k[0].toLowerCase()+k.slice(1),el=$('f'+k);if(el)el.value=x[key]||''});$('fStatus').value=x.status||ST[0];$('fPriority').value=x.priority||'B';let z=x.scoring||{};[['sFit','fit'],['sBudget','budget'],['sContact','contact'],['sLocal','local'],['sSport','sport'],['sRse','rse']].forEach(a=>{if(z[a[1]]!=null)$(a[0]).value=z[a[1]]});score();$('fPriority').value=x.priority||prio(n($('scoreTotal').textContent));$('deleteProspectBtn').classList.remove('hidden');$('prospectModal').classList.add('open')}
function score(){let A=[['sFit','svFit'],['sBudget','svBudget'],['sContact','svContact'],['sLocal','svLocal'],['sSport','svSport'],['sRse','svRse']],t=0;A.forEach(a=>{let v=n($(a[0]).value);$(a[1]).textContent=v;t+=v});$('scoreTotal').textContent=t;if(!edit)$('fPriority').value=prio(t)}
function collect(){let t=n($('scoreTotal').textContent);return{id:edit||uid(),company:$('fCompany').value.trim(),sector:$('fSector').value.trim(),location:$('fLocation').value.trim(),website:$('fWebsite').value.trim(),status:$('fStatus').value,priority:$('fPriority').value,contact:$('fContact').value.trim(),role:$('fRole').value.trim(),email:$('fEmail').value.trim(),phone:$('fPhone').value.trim(),linkedin:$('fLinkedin').value.trim(),potential:n($('fPotential').value),ask:n($('fAsk').value),signed:n($('fSigned').value),lastContact:$('fLastContact').value,nextDate:$('fNextDate').value,nextAction:$('fNextAction').value.trim(),startDate:$('fStartDate').value,renewal:$('fRenewal').value,tags:$('fTags').value.trim(),angle:$('fAngle').value.trim(),notes:$('fNotes').value.trim(),score:t,scoring:{fit:n($('sFit').value),budget:n($('sBudget').value),contact:n($('sContact').value),local:n($('sLocal').value),sport:n($('sSport').value),rse:n($('sRse').value)}}}
function saveP(){let x=collect();if(!x.company)return toast('Le nom de l’entreprise est obligatoire.');let i=D.items.findIndex(a=>a.id===x.id);i>=0?D.items[i]=x:D.items.push(x);save();$('prospectModal').classList.remove('open');render();toast(i>=0?'Prospect mis à jour.':'Prospect ajouté.')}
function del(){if(!edit)return;let x=item(edit);if(x&&confirm('Supprimer '+x.company+' ?')){D.items=D.items.filter(a=>a.id!==edit);save();$('prospectModal').classList.remove('open');render();toast('Prospect supprimé.')}}
function approach(){let c=$('fCompany').value.trim()||'ce prospect',a=$('fAngle').value.trim(),tags=$('fTags').value.trim()||'performance, jeunesse, visibilité et ancrage territorial',m=n($('fAsk').value)||n($('fPotential').value),s=n($('scoreTotal').textContent);$('approachContent').innerHTML=`<h3>Approche recommandée — ${esc(c)}</h3><p><strong>Priorité :</strong> ${prio(s)} • score ${s}/100</p><p><strong>Angle :</strong> ${esc(a||'Relier le projet ROAD TO P1 à '+tags+'.')}</p><p><strong>Interlocuteur cible :</strong> ${esc($('fContact').value||'communication / marketing / RSE / direction')}</p><p><strong>Montant à présenter :</strong> ${m?money(m):'à définir après qualification'}</p><p><strong>Message clé :</strong> partenariat concret et mesurable autour de jeunes pilotes et de l’égalité des chances dans le sport automobile.</p>`;$('approachWrap').classList.remove('hidden')}
function demo(){if(D.items.length&&!confirm('Ajouter les données de démonstration ?'))return;let y=new Date().getFullYear();D.items.push({id:uid(),company:'Entreprise Démo Alpha',sector:'Mobilité',location:'Grand Est',status:'À contacter',priority:'A',contact:'Camille Martin',role:'Communication',potential:8000,ask:6000,signed:0,nextDate:today(),nextAction:'Premier contact',tags:'mobilité, jeunesse, innovation',angle:'Innovation et jeunes pilotes',notes:'Démonstration',score:84,scoring:{fit:18,budget:16,contact:12,local:13,sport:13,rse:12}},{id:uid(),company:'Entreprise Démo Beta',sector:'Assurance',location:'France',status:'Proposition envoyée',priority:'A',contact:'Alex Durand',role:'Partenariats',potential:12000,ask:10000,signed:0,tags:'sport, sécurité, jeunesse',notes:'Démonstration',score:78,scoring:{fit:16,budget:18,contact:11,local:9,sport:13,rse:11}},{id:uid(),company:'Entreprise Démo Gamma',sector:'Industrie',location:'Marne',status:'Signé',priority:'B',contact:'Morgan Petit',role:'Direction',potential:5000,ask:5000,signed:5000,startDate:y+'-02-01',renewal:(y+1)+'-01-15',tags:'local, industrie, jeunesse',notes:'Démonstration',score:67,scoring:{fit:14,budget:12,contact:12,local:14,sport:7,rse:8}});save();render();toast('Données de démonstration ajoutées.')}
function research(){let o={geo:$('rGeo').value.trim(),sectors:$('rSectors').value.trim(),size:$('rSize').value.trim(),affinity:$('rAffinity').value.trim(),budget:$('rBudget').value.trim(),notes:$('rNotes').value.trim()};localStorage.setItem(R,JSON.stringify(o));showResearch();toast('Brief de recherche enregistré.')}
function showResearch(){let o={};try{o=JSON.parse(localStorage.getItem(R)||'{}')}catch(e){};['Geo','Sectors','Size','Affinity','Budget','Notes'].forEach(k=>$('r'+k).value=o[k.toLowerCase()]||'');let p=[];if(o.geo)p.push('<strong>Zone :</strong> '+esc(o.geo));if(o.sectors)p.push('<strong>Secteurs :</strong> '+esc(o.sectors));if(o.size)p.push('<strong>Cible :</strong> '+esc(o.size));if(o.affinity)p.push('<strong>Affinités :</strong> '+esc(o.affinity));if(o.budget)p.push('<strong>Budget :</strong> '+esc(o.budget));$('researchSummary').innerHTML=p.length?p.join('<br>'):'Aucun brief pour le moment.'}
function logo(){let i=$('officialLogo');fetch('https://raw.githubusercontent.com/felixbruno1973-design/road-to-p1-dynamics/main/index.html').then(r=>r.text()).then(t=>{let m=t.match(/<img class="official-logo" src="(data:image\/jpeg;base64,[^"]+)"/);if(m)i.src=m[1]}).catch(()=>{})}
function init(){load();fill();showResearch();render();document.querySelectorAll('.nav button').forEach(b=>b.onclick=()=>sw(b.dataset.view));$('addProspectBtn').onclick=()=>{reset();$('prospectModal').classList.add('open')};$('closeModal').onclick=()=> $('prospectModal').classList.remove('open');$('saveProspectBtn').onclick=saveP;$('deleteProspectBtn').onclick=del;$('prepareApproachBtn').onclick=approach;$('demoBtn').onclick=demo;$('saveResearchBtn').onclick=research;['sFit','sBudget','sContact','sLocal','sSport','sRse'].forEach(id=>$(id).oninput=score);['pSearch','pStatus','pPriority','pSector'].forEach(id=>$(id).oninput=()=>{prospects();bind()});$('resetFilters').onclick=()=>{$('pSearch').value='';$('pStatus').value=$('pPriority').value=$('pSector').value='all';prospects();bind()};$('prospectModal').onclick=e=>{if(e.target===$('prospectModal'))$('prospectModal').classList.remove('open')};document.addEventListener('keydown',e=>{if(e.key==='Escape')$('prospectModal').classList.remove('open')});logo()}
init();})();
