(()=>{'use strict';
const DATA={
  'Groupe Neubauer':[
    {level:'1',title:'Direction marketing / communication / partenariats',priority:'PRIORITÉ 1',status:'À identifier',name:'Décideur sponsoring / communication',role:'Responsable marketing, communication ou partenariats Groupe',email:'',phone:'',address:'227 boulevard Anatole France, 93200 Saint-Denis',action:'Identifier le nom direct puis adresser une proposition personnalisée. À défaut, passer par le contact Groupe pour demander le bon interlocuteur.',source:'https://www.neubauer.fr/mentions-legales'},
    {level:'2',title:'Direction générale',priority:'PRIORITÉ 2',status:'Identifié',name:'Leila NEUBAUER',role:'Directrice générale / directrice de publication',email:'',phone:'01 49 22 12 12',address:'227 boulevard Anatole France, 93200 Saint-Denis',action:'Approche dirigeante si le projet est déjà structuré : présenter en quelques lignes l’intérêt stratégique, puis demander l’orientation vers le décideur partenariat.',source:'https://boutique.neubauer.fr/conditions-generales-de-vente/'},
    {level:'3',title:'Contact Groupe',priority:'PORTE D’ENTRÉE',status:'Vérifié',name:'NEUBAUER Groupe — contact général',role:'Accueil / orientation Groupe',email:'contact@neubauer.fr',phone:'01 49 22 12 12',address:'227 boulevard Anatole France, 93200 Saint-Denis',action:'Utiliser ce canal pour obtenir le nom et les coordonnées du responsable sponsoring / marketing si le décideur direct n’est pas identifié.',form:'https://boutique.neubauer.fr/aide-et-contact/',source:'https://www.neubauer.fr/mentions-legales'},
    {level:'4',title:'Activation locale / concession',priority:'ACTIVATION',status:'Vérifié',name:'Village NEUBAUER — Saint-Denis',role:'Pôle automobile multimarques / activation locale',email:'',phone:'01 49 22 12 40',address:'233 boulevard Anatole France, 93200 Saint-Denis',action:'Proposer une activation concrète : exposition kart, invitation course, simulateur, événement clients ou contenu social. Le Village publie plusieurs lignes téléphoniques selon les marques ; celle-ci correspond au point Volkswagen.',source:'https://www.neubauer.fr/concessions/levillageneubauer'}
  ]
};
const E=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function generic(name){const K=window.RTP102_KNOWLEDGE||{},d=K[name]||{},v=d.verified||{};return[
 {level:'1',title:'Marketing / communication / partenariats',priority:'PRIORITÉ 1',status:'À identifier',name:'Décideur partenariat',role:(d.c||[])[0]||'Responsable sponsoring / communication',action:'Identifier la personne qui décide réellement des partenariats et préparer une approche personnalisée.'},
 {level:'2',title:'Direction générale',priority:'PRIORITÉ 2',status:(d.l||[]).length?'Identifié':'À identifier',name:(d.l||[])[0]||'Dirigeant à identifier',role:'Direction / arbitrage',action:'À utiliser pour une recommandation interne, une mise en relation ou une escalade après qualification du projet.'},
 {level:'3',title:'Contact Groupe',priority:'PORTE D’ENTRÉE',status:v.name?'Vérifié':'À enrichir',name:v.name||'Contact général à rechercher',role:v.role||'Accueil / orientation',email:v.email||'',phone:v.phone||'',address:v.address||'',form:v.form||'',source:v.source||'',action:'Demander explicitement le nom et les coordonnées du responsable sponsoring, communication ou partenariats.'},
 {level:'4',title:'Contact local / établissement',priority:'ACTIVATION',status:'À enrichir',name:'Agence, magasin, concession ou site local',role:'Relais territorial',action:'Chercher un point de contact local pouvant porter une activation terrain ou recommander le dossier au siège.'}
]}
function style(){if(document.getElementById('r103style'))return;const s=document.createElement('style');s.id='r103style';s.textContent=`.r103wrap{grid-column:1/-1;border:1px solid #394852;border-radius:12px;background:#0d151a;padding:12px}.r103head{display:flex;justify-content:space-between;gap:12px;align-items:flex-start;margin-bottom:10px}.r103head h5{margin:0;font-size:11px;text-transform:uppercase;letter-spacing:.1em;color:#ff777c}.r103head p{margin:3px 0 0!important;font-size:9px!important;color:#82909a!important}.r103flow{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:8px}.r103contact{border:1px solid #2d3942;border-radius:10px;background:#10181e;padding:10px;min-width:0}.r103top{display:flex;justify-content:space-between;gap:8px;align-items:flex-start}.r103level{width:24px;height:24px;display:grid;place-items:center;border-radius:50%;background:#291316;border:1px solid #a5383e;color:#fff;font-size:10px;font-weight:900}.r103priority{font-size:8px;font-weight:900;color:#ff9da1;letter-spacing:.06em;text-align:right}.r103contact h6{margin:8px 0 5px;font-size:11px;color:#eef2f4}.r103name{font-size:11px;font-weight:900;color:#dfe5e8}.r103role{font-size:9px;color:#87949c;margin:2px 0 8px}.r103row{font-size:9.5px;color:#c2cbd0;margin:4px 0;overflow-wrap:anywhere}.r103row a{color:#e8edf0}.r103action{margin-top:8px;padding-top:8px;border-top:1px solid rgba(255,255,255,.06);font-size:9.5px;line-height:1.4;color:#aeb9bf}.r103badges{display:flex;gap:5px;flex-wrap:wrap;margin-top:8px}.r103badge{display:inline-flex;padding:3px 6px;border-radius:999px;border:1px solid #3b4650;font-size:8px;font-weight:900}.r103badge.ok{border-color:#2f6b49;background:#10261a;color:#7fe0a5}.r103badge.wait{border-color:#57462b;background:#231c0f;color:#f2c56f}.r103links{display:flex;gap:6px;flex-wrap:wrap;margin-top:7px}.r103links a{border:1px solid #3a464e;background:#172028;border-radius:7px;padding:5px 7px;font-size:8px;font-weight:800}.r103strategy{margin-top:10px;border:1px solid #563b3e;border-radius:10px;background:linear-gradient(180deg,#1d1417,#10181e);padding:10px;font-size:10px;line-height:1.5;color:#c8d0d4}.r103strategy b{color:#fff}@media(max-width:1100px){.r103flow{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:700px){.r103flow{grid-template-columns:1fr}}`;document.head.appendChild(s)}
function card(x){const statusClass=/Vérifié|Identifié/.test(x.status)?'ok':'wait';const contact=[x.email&&`<div class="r103row">✉ <a href="mailto:${E(x.email)}">${E(x.email)}</a></div>`,x.phone&&`<div class="r103row">☎ <a href="tel:${E(x.phone.replace(/\s/g,''))}">${E(x.phone)}</a></div>`,x.address&&`<div class="r103row">⌖ ${E(x.address)}</div>`].filter(Boolean).join('');const links=[x.form&&`<a href="${E(x.form)}" target="_blank" rel="noopener">Formulaire ↗</a>`,x.source&&`<a href="${E(x.source)}" target="_blank" rel="noopener">Source ↗</a>`].filter(Boolean).join('');return `<div class="r103contact"><div class="r103top"><span class="r103level">${E(x.level)}</span><span class="r103priority">${E(x.priority)}</span></div><h6>${E(x.title)}</h6><div class="r103name">${E(x.name)}</div><div class="r103role">${E(x.role)}</div>${contact}<div class="r103badges"><span class="r103badge ${statusClass}">${E(x.status)}</span></div>${links?`<div class="r103links">${links}</div>`:''}<div class="r103action">${E(x.action)}</div></div>`}
function stamp(){document.title='ROAD TO P1 Partners — V1.0.3';const v=document.querySelector('.version');if(v)v.innerHTML='ROAD TO P1 Partners<br>V1.0.3';const f=document.querySelector('.footer');if(f)f.textContent='ROAD TO P1 Partners • V1.0.3 • Données enregistrées localement dans ce navigateur';const m=document.querySelector('#view-research .panel-head .meta');if(m&&/V1\.0\.2/.test(m.textContent))m.textContent='V1.0.3'}
function inject(){style();stamp();const w=document.getElementById('r2Work'),h=w?.querySelector('.r2head h3'),g=w?.querySelector('.r2knowledge-grid');if(!h||!g)return;const name=h.textContent.trim();let old=g.querySelector('.r103wrap');if(old?.dataset.company===name)return;old?.remove();const rows=DATA[name]||generic(name),x=document.createElement('div');x.className='r103wrap';x.dataset.company=name;x.innerHTML=`<div class="r103head"><div><h5>Stratégie de contact — 4 niveaux</h5><p>Qui contacter, dans quel ordre et par quel canal.</p></div><span class="r103badge ok">V1.0.3</span></div><div class="r103flow">${rows.map(card).join('')}</div><div class="r103strategy"><b>Ordre conseillé :</b> commencer par le décideur marketing / partenariats lorsqu’il est identifié. Sinon utiliser le contact Groupe pour obtenir son nom. La direction générale sert d’accélérateur ou d’escalade ; le contact local sert surtout à construire une activation concrète et à créer une recommandation interne.</div>`;g.insertBefore(x,g.children[2]||null)}
function boot(){stamp();inject();const w=document.getElementById('r2Work');if(w)new MutationObserver(()=>{stamp();inject()}).observe(w,{childList:true,subtree:true});document.querySelector('[data-view="research"]')?.addEventListener('click',()=>setTimeout(()=>{stamp();inject()},20))}
setTimeout(boot,0);
})();
