(()=>{'use strict';
const STORE='roadToP1PartnersV104Scores';
const DEFAULTS={
 '1':{interest:95,access:45},
 '2':{interest:85,access:55},
 '3':{interest:65,access:90},
 '4':{interest:75,access:80}
};
const E=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function readScores(){try{return JSON.parse(localStorage.getItem(STORE)||'{}')}catch(e){return{}}}
function writeScores(x){localStorage.setItem(STORE,JSON.stringify(x))}
function getScore(company,level){const all=readScores(),k=company+'::'+level,d=DEFAULTS[level]||{interest:70,access:60};return Object.assign({},d,all[k]||{})}
function total(s){return Math.round(s.interest*.65+s.access*.35)}
function scoreLabel(n){return n>=85?'Très haute':n>=70?'Haute':n>=55?'Moyenne':'À travailler'}
function style(){if(document.getElementById('r104style'))return;const s=document.createElement('style');s.id='r104style';s.textContent=`
.r104scores{display:grid;grid-template-columns:1fr 1fr 1fr;gap:5px;margin-top:9px}.r104score{border:1px solid #35424b;border-radius:8px;background:#0c1318;padding:6px 5px;text-align:center}.r104score span{display:block;font-size:7px;text-transform:uppercase;letter-spacing:.06em;color:#7f8b94}.r104score b{display:block;margin-top:2px;font-size:13px;color:#eef2f4}.r104score.priority{border-color:#654045;background:#1b1215}.r104score.priority b{color:#ff969b}.r104rank{margin-top:6px;font-size:8px;color:#9da9b0;text-align:right}.r104editbtn{margin-right:auto!important;border-color:#6a3d41!important;background:#241417!important;color:#ffdadd!important}.r104overlay{position:fixed;inset:0;z-index:99999;background:rgba(3,6,8,.78);backdrop-filter:blur(4px);display:grid;place-items:center;padding:18px}.r104overlay[hidden]{display:none}.r104modal{width:min(880px,96vw);max-height:92vh;overflow:auto;border:1px solid #3d4a53;border-radius:16px;background:#0d1419;box-shadow:0 24px 80px rgba(0,0,0,.55)}.r104modalhead{display:flex;justify-content:space-between;gap:10px;align-items:center;padding:14px 16px;border-bottom:1px solid rgba(255,255,255,.07)}.r104modalhead h3{margin:0;font-size:16px}.r104close{border:1px solid #3b4650;background:#161f25;color:#fff;border-radius:8px;width:34px;height:34px;font-size:18px}.r104body{padding:14px 16px}.r104grid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.r104full{grid-column:1/-1}.r104body label{display:block;margin:0 0 5px;font-size:9px;text-transform:uppercase;letter-spacing:.08em;color:#8d99a1}.r104body input,.r104body textarea{width:100%;box-sizing:border-box;border:1px solid #35424b;background:#10181e;color:#eef2f4;border-radius:9px;padding:10px;font:inherit}.r104body textarea{min-height:260px;resize:vertical;line-height:1.5}.r104voicebar{display:flex;gap:7px;flex-wrap:wrap;margin:8px 0 0}.r104voice{border:1px solid #475761;background:#162129;color:#e6ecef;border-radius:8px;padding:8px 10px;font-size:10px;font-weight:800}.r104voice.live{border-color:#9d3a43;background:#301216;color:#ffb4b8}.r104hint{font-size:9px;color:#7f8b94;margin-top:8px;line-height:1.45}.r104modalactions{display:flex;justify-content:flex-end;gap:8px;padding:12px 16px;border-top:1px solid rgba(255,255,255,.07)}.r104cancel,.r104save{border-radius:9px;padding:9px 13px;font-weight:800}.r104cancel{border:1px solid #3b4650;background:#161f25;color:#e6ecef}.r104save{border:1px solid #a33c43;background:#812e34;color:#fff}@media(max-width:700px){.r104grid{grid-template-columns:1fr}.r104full{grid-column:auto}.r104body textarea{min-height:220px}.r104scores{grid-template-columns:1fr 1fr 1fr}}
`;document.head.appendChild(s)}
function stamp(){const ver=window.RTP_VERSION_LOCK||'1.0.4';document.title='ROAD TO P1 Partners — V'+ver;const v=document.querySelector('.version');if(v)v.innerHTML='ROAD TO P1 Partners<br>V'+ver;const f=document.querySelector('.footer');if(f)f.textContent='ROAD TO P1 Partners • V'+ver+' • Données enregistrées localement dans ce navigateur';const m=document.querySelector('#view-research .panel-head .meta');if(m)m.textContent='V'+ver}
function injectScores(){document.querySelectorAll('.r103wrap').forEach(w=>{const company=w.dataset.company||'';w.querySelectorAll('.r103contact').forEach(card=>{if(card.querySelector('.r104scores'))return;const level=card.querySelector('.r103level')?.textContent.trim()||'';const sc=getScore(company,level),p=total(sc);const box=document.createElement('div');box.className='r104scores';box.innerHTML=`<div class="r104score"><span>Intérêt</span><b>${sc.interest}</b></div><div class="r104score"><span>Accessibilité</span><b>${sc.access}</b></div><div class="r104score priority"><span>Priorité</span><b>${p}</b></div>`;card.appendChild(box);const r=document.createElement('div');r.className='r104rank';r.textContent=`${scoreLabel(p)} • 65% intérêt / 35% accessibilité`;card.appendChild(r)})})}
function modal(){let o=document.getElementById('r104Overlay');if(o)return o;o=document.createElement('div');o.id='r104Overlay';o.className='r104overlay';o.hidden=true;o.innerHTML=`<div class="r104modal" role="dialog" aria-modal="true" aria-labelledby="r104Title"><div class="r104modalhead"><h3 id="r104Title">Modifier le mail proposé</h3><button class="r104close" id="r104Close" aria-label="Fermer">×</button></div><div class="r104body"><div class="r104grid"><div><label>Contact</label><input id="r104Contact"></div><div><label>E-mail</label><input id="r104Email" type="email"></div><div class="r104full"><label>Objet</label><input id="r104Subject"></div><div class="r104full"><label>Message</label><textarea id="r104Message"></textarea><div class="r104voicebar"><button class="r104voice" id="r104VoiceSubject">🎙 Dicter l’objet</button><button class="r104voice" id="r104VoiceMessage">🎙 Dicter le message</button><button class="r104voice" id="r104VoiceStop">■ Arrêter la dictée</button></div><div class="r104hint" id="r104VoiceHint">Vous pouvez modifier librement au clavier. La dictée vocale utilise la reconnaissance vocale du navigateur lorsqu’elle est disponible.</div></div></div></div><div class="r104modalactions"><button class="r104cancel" id="r104Cancel">Annuler</button><button class="r104save" id="r104Apply">Enregistrer les modifications</button></div></div>`;document.body.appendChild(o);o.querySelector('#r104Close').onclick=closeModal;o.querySelector('#r104Cancel').onclick=closeModal;o.addEventListener('click',e=>{if(e.target===o)closeModal()});o.querySelector('#r104Apply').onclick=applyMail;o.querySelector('#r104VoiceSubject').onclick=()=>startVoice('subject');o.querySelector('#r104VoiceMessage').onclick=()=>startVoice('message');o.querySelector('#r104VoiceStop').onclick=stopVoice;return o}
let recognition=null,voiceTarget='message';
function stopVoice(){if(recognition){try{recognition.stop()}catch(e){}recognition=null}document.querySelectorAll('.r104voice').forEach(b=>b.classList.remove('live'));const h=document.getElementById('r104VoiceHint');if(h)h.textContent='Dictée arrêtée. Vous pouvez continuer au clavier ou relancer le micro.'}
function startVoice(target){voiceTarget=target;const SR=window.SpeechRecognition||window.webkitSpeechRecognition,h=document.getElementById('r104VoiceHint');if(!SR){if(h)h.textContent='La reconnaissance vocale n’est pas disponible dans ce navigateur. La modification au clavier reste disponible.';return}stopVoice();recognition=new SR();recognition.lang='fr-FR';recognition.continuous=true;recognition.interimResults=false;const btn=document.getElementById(target==='subject'?'r104VoiceSubject':'r104VoiceMessage');btn?.classList.add('live');if(h)h.textContent='Micro actif — parlez normalement. Le texte reconnu sera ajouté au champ sélectionné.';recognition.onresult=e=>{const text=Array.from(e.results).slice(e.resultIndex).filter(r=>r.isFinal).map(r=>r[0].transcript).join(' ').trim();if(!text)return;const field=document.getElementById(voiceTarget==='subject'?'r104Subject':'r104Message');if(!field)return;const sep=field.value&& !/\s$/.test(field.value)?' ':'';field.value+=sep+text};recognition.onerror=e=>{if(h)h.textContent='Dictée interrompue : '+(e.error||'erreur micro')+'. Vous pouvez continuer au clavier.';stopVoice()};recognition.onend=()=>{document.querySelectorAll('.r104voice').forEach(b=>b.classList.remove('live'))};try{recognition.start()}catch(e){if(h)h.textContent='Impossible de démarrer le micro dans ce navigateur.'}}
function openModal(){const o=modal(),get=id=>document.getElementById(id);get('r104Contact').value=get('r2CN')?.value||'';get('r104Email').value=get('r2CE')?.value||'';get('r104Subject').value=get('r2Sub')?.value||'';get('r104Message').value=get('r2Body')?.value||'';get('r104VoiceHint').textContent='Vous pouvez modifier librement au clavier. La dictée vocale utilise la reconnaissance vocale du navigateur lorsqu’elle est disponible.';o.hidden=false;setTimeout(()=>get('r104Message')?.focus(),20)}
function closeModal(){stopVoice();const o=document.getElementById('r104Overlay');if(o)o.hidden=true}
function applyMail(){const map=[['r104Contact','r2CN'],['r104Email','r2CE'],['r104Subject','r2Sub'],['r104Message','r2Body']];for(const [a,b] of map){const src=document.getElementById(a),dst=document.getElementById(b);if(src&&dst)dst.value=src.value}document.getElementById('r2SaveMail')?.click();closeModal()}
function injectMailButton(){const cards=[...document.querySelectorAll('#r2Work .r2card.full')];const card=cards.find(x=>/mail d.approche|mail d’approche/i.test(x.querySelector('h4')?.textContent||''));if(!card||card.querySelector('#r104EditMail'))return;const actions=card.querySelector('.r2actions');if(!actions)return;const b=document.createElement('button');b.className='btn r104editbtn';b.id='r104EditMail';b.textContent='✎ Modifier mail';b.onclick=openModal;actions.insertBefore(b,actions.firstChild)}
function inject(){style();stamp();injectScores();injectMailButton()}
function boot(){modal();inject();const w=document.getElementById('r2Work');if(w)new MutationObserver(()=>queueMicrotask(inject)).observe(w,{childList:true,subtree:true});document.querySelector('[data-view="research"]')?.addEventListener('click',()=>setTimeout(inject,30));setInterval(stamp,1200);document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!document.getElementById('r104Overlay')?.hidden)closeModal()})}
setTimeout(boot,0);
})();
